# -*- coding: utf-8 -*-
"""08 - Projeto Mercado Financeiro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q10N9BswxJhMnbha6IRjqdeDJrVM3mEh

# **Ciência de Dados para Finanças** <p>
**por: @Odemir Depieri Jr** - [Linkedin](https://www.linkedin.com/in/odemir-depieri-jr/) <p>
**por: @Ronisson Lucas Calmon da Conceição** - [Linkedin](https://www.linkedin.com/in/ronisson-lucas-calmon-da-concei%C3%A7%C3%A3o-7aa884202/) <p>
[Página do Curso](https://)
"""

# Dados para download
Base_Dados_Nesse_Link = 'https://docs.google.com/spreadsheets/d/1r0_Vs5QX1ef5X1MZCbDg8kcqm-my3rSn/edit?usp=sharing&ouid=108903987275959757465&rtpof=true&sd=true'

print('Dados salvo no Google Driver')
print( Base_Dados_Nesse_Link )

# Libs Necessárias

# Libs para Modelagem e Matrizez
import numpy as np
import pandas as pd

# Libs para anaálises gráficas
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

# Lib para ignorar avisos
import warnings

# Desabilitando avisos
warnings.filterwarnings('ignore')

# Lendo os dados
Base_Dados = pd.read_excel('Vase_004 - Magalu - Sem Resolução.xlsx')

# Verificando
Base_Dados.head()

Base_Dados.shape

Base_Dados.info()

Base_Dados.describe()

# Series Temporais
Dados = Base_Dados.set_index('Data')

Dados.head()

plt.style.use('seaborn-darkgrid')
plt.figure( figsize=(16, 5) )
plt.title('Análise das ações da magalu - Fechamento', fontsize=15, loc='left')
plt.plot( Dados.index, Dados['Fechamento'] )

plt.xlabel('Período da Coração')
plt.ylabel('Valor da Ação (R$)');

Dados.tail()

Media_Movel = Dados['Fechamento'].rolling(5).mean()
Media_Tendencia = Dados['Fechamento'].rolling(30).mean()

plt.style.use('seaborn-darkgrid')
plt.figure( figsize=(16, 5) )
plt.title('Análise das ações da magalu - Fechamento', fontsize=15, loc='left')

plt.plot( Dados.index, Dados['Fechamento'] )
plt.plot( Dados.index, Media_Movel )
plt.plot( Dados.index, Media_Tendencia )

plt.xlabel('Período da Coração')
plt.ylabel('Valor da Ação (R$)');

sns.boxplot( data=Dados, x='Fechamento')

# Boxplot Mensal 

Base_Dados['Mes'] = Base_Dados['Data'].dt.month

plt.figure( figsize=(16, 5) )
sns.boxplot( data=Base_Dados, x='Mes', y='Fechamento' );

Base_Dados.groupby(['Mes']).describe()['Fechamento']

# 
Grafico = go.Figure(
    data=[
          go.Candlestick(
              x= Dados.index,
              open = Dados['Abertura'],
              high = Dados['Maior'],
              low = Dados['Menor'],
              close = Dados['Fechamento'],
          )
    ]
)

Grafico.update_layout( xaxis_rangeslider_visible=False )

Grafico.show()

